#ifndef PARSER_H
#define PARSER_H

#include "dom.h"
#include "token.h"

// Function called by the lexer to get the next token.
// Defined in lexer.l (yyin) and implemented in lexer.c (generated by flex).
extern Token get_next_token();

// Recursive Descent Parsing function
// Returns the root of the constructed DOM tree or NULL on critical error.
DOMNode *parse_document(void);

// Reports a parsing error
void parser_error(const char *message);

#endif // PARSER_H